### ISSUE TITLE
Add optional `mongod` config file path to versions.json

### ISSUE THREAD

**Issue by stennie** [jorge-imperial/create_mongodb_logs#3]
To test with config variations for the same version of MongoDB (for example, using different storage engines or security configurations) I think it would be helpful to be able to have an optional `config` file path.

For example:

  {
     "name": "3.4.9",
     "path": "/usr/local/m/versions/3.4.9/bin",
     "conf": "default.conf"
   },
  {
     "name": "3.4.9",
     "path": "/usr/local/m/versions/3.4.9/bin",
     "conf": "mmap.conf",
   }

This can currently be handled with multiple version files and invocations of `create_mongo_log.py`, so feel free to close if that sounds like scope creep. The config files would also have to be factored into the output path names (for example: `mongod-3.4.9-default.log` vs `mongod-3.4.9-mmap.log`).

Thanks,
Stennie

**Comment by jorge-imperial** [comment]
Added capability in a87b5b7.

**Comment by stennie** [comment]
Nice .. thanks @jorge-imperial !
